# Generated by Django 5.0.6 on 2024-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='donor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='total_number_of_donations',
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_donation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donation_location',
            field=models.CharField(choices=[('Nairobi Blood Transfusion Centre', 'Nairobi Blood Transfusion Centre'), ('Mombasa Blood Transfusion Centre', 'Mombasa Blood Transfusion Centre'), ('Kisumu Blood Transfusion Centre', 'Kisumu Blood Transfusion Centre'), ('Embu Blood Transfusion Centre', 'Embu Blood Transfusion Centre'), ('Nakuru Blood Transfusion Centre', 'Nakuru Blood Transfusion Centre'), ('Eldoret Blood Transfusion Centr', 'Eldoret Blood Transfusion Centr')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phonenumber', 'Phonenumber')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='type_donation',
            field=models.CharField(blank=True, choices=[('One-time donations', 'One Time'), ('Recurring donations', 'Recurring'), ('Planned donations', 'Planned'), ('Tribute or memorial donations', 'Tri Mem'), ('Stock donations', 'Stock'), ('In-kind donations', 'Kind'), ('Matching donations', 'Matching'), ('Workplace donations', 'Workplace'), ('Event donations', 'Event')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
