# Generated by Django 5.0.6 on 2024-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_rename_donor_donor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
