# Generated by Django 5.0.6 on 2024-06-04 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donor_weight_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_of_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donation_location',
            field=models.CharField(blank=True, choices=[('Nairobi Blood Transfusion Centre', 'Nairobi Blood Transfusion Centre'), ('Mombasa Blood Transfusion Centre', 'Mombasa Blood Transfusion Centre'), ('Kisumu Blood Transfusion Centre', 'Kisumu Blood Transfusion Centre'), ('Embu Blood Transfusion Centre', 'Embu Blood Transfusion Centre'), ('Nakuru Blood Transfusion Centre', 'Nakuru Blood Transfusion Centre'), ('Eldoret Blood Transfusion Centr', 'Eldoret Blood Transfusion Centr')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
