# Generated by Django 5.0.6 on 2024-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donor_date_of_donation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
