# Generated by Django 5.0.6 on 2024-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donor_created_donor_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
