# Generated by Django 5.0.6 on 2024-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_donor_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='number_of_donations',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
