# Generated by Django 5.0.6 on 2024-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_donor_number_of_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_photo',
            field=models.ImageField(blank=True, default='no_pic.png', upload_to='donors'),
        ),
    ]
