# Generated by Django 5.0.6 on 2024-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_alter_donor_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='profile_photo',
            field=models.ImageField(blank=True, default='no_pic.jpg', upload_to='donors'),
        ),
    ]
