# Generated by Django 5.0.6 on 2024-06-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_rename_description_appointment_benefiaciary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='benefiaciary',
            new_name='beneficiary',
        ),
    ]
