# Generated by Django 5.0.6 on 2024-06-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0015_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-created',)},
        ),
    ]
