# Generated by Django 5.0.6 on 2024-06-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0016_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCLED', 'CANCLED')], default='PENDING', max_length=20),
        ),
    ]
