# Generated by Django 5.0.6 on 2024-06-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0018_donor_number_of_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='number_of_donations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
