# Generated by Django 5.0.6 on 2024-06-14 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0019_alter_donor_number_of_donations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='DonorAppointment',
        ),
    ]
