# Generated by Django 5.0.6 on 2024-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0020_rename_appointment_donorappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='amount_of_donation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donorappointment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
