# Generated by Django 5.0.6 on 2024-06-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0021_donor_amount_of_donation_donorappointment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorappointment',
            name='amount',
        ),
    ]
