# Generated by Django 5.0.6 on 2024-07-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0026_rename_donations_donordonations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordonations',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
