# Generated by Django 5.0.6 on 2024-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0027_alter_donordonations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordonations',
            name='blood_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of blood donated in ml', max_digits=10),
        ),
    ]
