# Generated by Django 5.0.6 on 2024-07-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0028_donordonations_blood_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of blood donated in ml', max_digits=10, null=True),
        ),
    ]
