# Generated by Django 5.0.6 on 2024-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0029_donor_blood_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of blood donated (bags)', max_digits=10, null=True),
        ),
    ]
