# Generated by Django 5.0.6 on 2024-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0031_alter_donor_amount_of_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='number_of_donations',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
