# Generated by Django 5.0.6 on 2024-07-10 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0032_alter_donor_number_of_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
