# Generated by Django 5.0.6 on 2024-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0033_alter_donor_last_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordonations',
            name='blood_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of blood donated (bags)', max_digits=10),
        ),
    ]
