# Generated by Django 5.0.6 on 2024-07-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0034_alter_donordonations_blood_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=12, null=True),
        ),
    ]
