# Generated by Django 5.0.6 on 2024-07-10 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0035_alter_donor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordonations',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donor'),
        ),
    ]
