# Generated by Django 5.0.6 on 2024-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Donations', 'Donation Report'), ('Appointments', 'Appointments  Report'), ('Blood Inventory', 'Blood Inventory Report'), ('Donors', 'Donors Report'), ('Patients', 'Patients Report'), ('Doctors', 'Doctors Report'), ('Financial', 'Financial Report')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ('-created',),
            },
        ),
    ]
