# Generated by Django 5.0.6 on 2024-06-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
