# Generated by Django 5.0.6 on 2024-06-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_medical_record_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='blood_type',
            new_name='blood_group',
        ),
    ]
