# Generated by Django 5.0.6 on 2024-07-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_amount_of_blood_used_patient_follow_up_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdonations',
            old_name='description',
            new_name='treatment_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='amount_of_blood_used',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment_notes',
        ),
        migrations.RemoveField(
            model_name='patientdonations',
            name='amount',
        ),
        migrations.AddField(
            model_name='patientdonations',
            name='amount_of_blood_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of blood donated in ml', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdonations',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
