# Generated by Django 5.0.6 on 2024-07-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_rename_description_patientdonations_treatment_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-created',), 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
