# Generated by Django 5.0.6 on 2024-07-10 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patient_address_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('default_notification_method', models.CharField(choices=[('email', 'Email'), ('phonenumber', 'Phonenumber')], default='email', max_length=255)),
                ('created', models.DateField(auto_now=True, null=True)),
                ('modified', models.DateField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_settings', to='patients.patient')),
            ],
        ),
    ]
