# Generated by Django 5.0.6 on 2024-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_patientsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdonations',
            name='amount_of_blood_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of blood Used (Bags)', max_digits=10, null=True),
        ),
    ]
