# Generated by Django 5.0.6 on 2024-06-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='no_appointments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
