# Generated by Django 5.0.6 on 2024-06-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('modified', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
