# Generated by Django 5.0.6 on 2024-06-14 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='DoctorNotification',
        ),
    ]
