# Generated by Django 5.0.6 on 2024-06-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_notification_doctornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='notify_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
