# Generated by Django 5.0.6 on 2024-06-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_rename_appointments_doctorappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointments',
            name='note',
            field=models.CharField(default='Always make sure to leave a comment', max_length=250),
        ),
    ]
