# Generated by Django 5.0.6 on 2024-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctorappointments_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointments',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ATTENTED', 'ATTENTED'), ('CANCLED', 'CANCLED')], default='PENDING', max_length=20),
        ),
    ]
