# Generated by Django 5.0.6 on 2024-06-14 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctorappointments_status'),
        ('donors', '0019_alter_donor_number_of_donations'),
        ('patients', '0006_patient_id_number_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointments',
            name='appointment_from',
        ),
        migrations.AddField(
            model_name='doctorappointments',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.donor'),
        ),
        migrations.AddField(
            model_name='doctorappointments',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
