# Generated by Django 5.0.6 on 2024-06-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_remove_doctorappointments_appointment_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
