# Generated by Django 5.0.6 on 2024-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_doctornotification_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointments',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CANCLED', 'CANCLED')], default='PENDING', max_length=20),
        ),
    ]
