# Generated by Django 5.0.6 on 2024-07-10 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_bloodinventory'),
        ('donors', '0031_alter_donor_amount_of_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodinventory',
            name='quantity_ml',
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.donor'),
        ),
        migrations.AddField(
            model_name='bloodinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of blood donated (bags)', max_digits=10),
        ),
    ]
