# Generated by Django 5.0.6 on 2024-07-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_remove_bloodinventory_quantity_ml_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodinventory',
            options={'verbose_name': 'Blood Inventory', 'verbose_name_plural': 'Blood Inventories'},
        ),
    ]
