# Generated by Django 5.0.6 on 2024-07-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_alter_bloodinventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='number_max_appointments',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Number of appointments a doctor can take per day', null=True),
        ),
    ]
