# Generated by Django 5.0.6 on 2024-07-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_alter_doctor_hospital_affiliated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
